### PR TITLE
enable aggressive-nsec

### PR DESCRIPTION
**Pull request by mibere**

### CODE REVIEW

**Comment by jedisct1** [comment]
I’m a little bit worried that it could break resolution of valid (as in “it works when I use a different resolver”) domain names. Arguably, authoritative servers are to blame, but from a user perspective, we may get “it doesn’t work with your resolver” complaints.

https://github.com/dns-violations/dns-violations/pull/64/files
https://community.cloudflare.com/t/problem-with-oneplus-com-and-postbank-de/29232

F5 and Akamai seem to be the champions at serving broken DNS records, but I’m not sure that whitelisting their domains on a case-by-case basis (can it even be done with Unbound?) is going to be manageable.

**Comment by jedisct1** [comment]
Given the number of signed zones, I’m also not convinced that it would translate to 65% less global traffic.

Most of the queries leading to a `NXDOMAIN` response are random crap sent by Google Chrome, typos in web pages and names in the `.local`, `.lan` and `.belkin` zones that shouldn’t have left the LAN. Still, these require recursive servers to hit root servers every time.

That’s something we may tackle by synthesizing `NXDOMAIN` responses when the TLD is unknown. This shouldn’t prevent new TLDs from being discovered. I have a plan to address this in encrypted-dns-server.

**Comment by publicarray** [comment]
I've enabled aggressive nsec on my [config](https://github.com/publicarray/dns-resolver-infra/blob/master/unbound/unbound.conf#L134) and noticed no brakage from my tiny amount of pages that I visit day to day. I know it's a super small sample size. In the config you'll see that I have made popular Undelegated TLDs local-zone so that they don't hit root. I always like to improve my config if you have any suggestions I'd like to hear them.

**Comment by publicarray** [comment]
2019-11-29T00 00-2019-12-05T23 59-all
Here a quick look at the `QTYPE for most popular Undelegated TLDs` from the L root zone: http://stats.dns.icann.org/hedgehog/

**Comment by mibere** [comment]
> F5 and Akamai seem to be the champions at serving broken DNS records

That's sad. But if they or others have strange/incorrect/non-compliant server configurations, we also could say "Sorry users, it's not our fault. We use a feature based on a RFC."

I currently have 'aggressive-nsec: yes' on [dnscrypt.one](https://github.com/DNSCrypt/dnscrypt-resolvers/pull/194)

**Comment by jedisct1** [comment]
Did you notice a significant decrease of upstream traffic since it was enabled?

**Comment by jedisct1** [comment]
Prometheus metrics to track the number of NXDOMAIN responses (both from upstream servers, and directly served to clients) have been added.

That will come in handy to measure the impact of these optimizations!

**Comment by jedisct1** [comment]
HedgeHog confirms that the amount of NXDOMAIN responses is insane: http://stats.dns.icann.org/plotcache/L-Root/rcode_volume/2019-12-06T00:00-2019-12-06T23:59-all.html

All these queries for `local`, `home`, etc. are out of control. What a waste.

**Comment by mibere** [comment]
> Did you notice a significant decrease of upstream traffic since it was enabled?

I guess it can be manually (so far never had contact with Prometheus) tracked by unbound-control's `num.query.aggressive.NXDOMAIN`, right?

```
num.query.aggressive.NXDOMAIN
       The number of queries answered using cached  NSEC  records  with
       NXDOMAIN RCODE.  These queries would otherwise have been sent to
       the internet, but are now answered using cached data.
```

**Comment by jedisct1** [comment]
Oh, indeed, I forgot about Unbound counters.

Without aggressive NSEC, about 13.1% of upstream queries return NXDOMAIN.

(and about 2% of the responses sent to clients are NXDOMAIN)

Screen Shot 2019-12-07 at 9 37 29 PM

I'm going to enable `aggressive.NXDOMAIN` now :)

**Comment by jedisct1** [comment]
Undelegated TLDs (`local`, `home`, etc.) are good to serve directly, but my guess is that a great deal of crap sent to root servers are not within these zones, but randomly-generated names from Google Chrome. These are unique enough that they don't appear in the HedgeHog list. So I'd like to see if whitelisting TLDs with a delegation wouldn't be more effective than blacklisting popular undelegated TLDs.

**Comment by mibere** [comment]
> I guess it can be manually (so far never had contact with Prometheus) tracked by unbound-control's `num.query.aggressive.NXDOMAIN`, right?

Doesn't work. With 'aggressive-nsec: no' _num.query.aggressive.NXDOMAIN_ is always '0'.

-----

Frank, you surely meant

> Without aggressive NSEC, about **2%** of upstream queries return NXDOMAIN.
>  
> (and about **13.1%** of the responses sent to clients are NXDOMAIN)

**Comment by jedisct1** [comment]
Aggressive NSEC doesn't make any visible difference. The number of responses from upstream resolvers that are NXDOMAIN now reached 21.6%

Screen Shot 2019-12-07 at 11 16 27 PM

**Comment by jedisct1** [comment]
Wait, the labels are not good in the first graph :)

**Comment by jedisct1** [comment]
Clients queries returning NXDOMAIN are insignificant (maybe the counters are not correct here).

But queries sent to upstream servers returning NXDOMAIN are super high, I think the numbers are correct here.
Screen Shot 2019-12-07 at 11 20 24 PM

**Comment by jedisct1** [comment]
```sh
$ unbound-control stats_noreset|egrep 'total.num.recursivereplies|aggressive.NXDOMAIN'
total.num.recursivereplies=96686
num.query.aggressive.NXDOMAIN=866
```

Turning on aggressive NSEC prevented 0.89% of queries to be sent to authoritative servers.

Definitely an improvement, but not really significant.

**Comment by publicarray** [comment]
I suspect a lot of NXDOMAIN responses are from PTR requests in-addr.arpa
```
$ unbound-control stats_noreset|egrep 'total.num.recursivereplies|NXDOMAIN'
total.num.recursivereplies=1363241
num.answer.rcode.NXDOMAIN=829149
num.query.aggressive.NXDOMAIN=16550
```

**Comment by jedisct1** [comment]
Oh indeed, that's very likely.

**Comment by jedisct1** [comment]
There is now an option to synthesize A and AAAA responses for unqualified hostnames. Seems to help quite a bit (turned on around 23:10)

Screen Shot 2019-12-07 at 11 52 22 PM

**Comment by jedisct1** [comment]
Anyway, let's merge this. We'll see if people complain :)

**Comment by mibere** [comment]
**Thanks** for your time and investigations.

**Comment by jedisct1** [comment]
Filtering A/AAAA queries for unqualified hostnames (after forwarding rules are evaluated) should actually be done in `dnscrypt-proxy`. There is no point in sending these queries to external servers, and it's bad for privacy.

There are (were?) some TLDs running webservers on the TLD itself, though. I'll try to scan all the TLDs to see what the current state of affairs is.

**Pull request merged**
